version: '3.1'
services:
  consumer-demo-db:
    image: postgres:14-alpine
    container_name: consumer-demo-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=consumer_db
      - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password

  producer-demo-db:
    image: postgres:14-alpine
    container_name: producer-demo-db
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=producer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password