version: '3.1'
services:
  consumer-demo-db:
    image: postgres:14-alpine
    container_name: consumer-demo-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=consumer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  producer-demo-db:
    image: postgres:14-alpine
    container_name: producer-demo-db
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=producer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  zookeeper-demo:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper-demo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka-demo:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-demo
    depends_on:
      - zookeeper-demo
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-demo:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop-demo:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop-demo
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka-demo
